In [1]:
import pandas as pd

In [2]:
#library imports API data
#import

In [3]:
# Region: Haut-Rhin (68)
df_locations = pd.read_csv('../data/ech_annonces_locations_68.csv',sep=';')
df_ventes = pd.read_csv('../data/ech_annonces_ventes_68.csv',sep=';')

In [4]:
df_locations.head()

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,date,INSEE_COM,IRIS,CODE_IRIS,TYP_IRIS_x,TYP_IRIS_y,GRD_QUART,UU2010,REG,DEP
0,immo-facile-52417007,pr,m,l,0,116,NaN,5,1250,NaN,...,2023-04,68159,0,681590000,Z,Z,6815900,68000,44,68
1,ag672097-382986683,pr,a,l,3,44,NaN,3,600,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
2,ag672097-383464082,pr,a,l,1,53,NaN,2,498,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
3,ag680864-383044166,pr,a,l,0,41,NaN,2,460,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68
4,ag672097-380998252,pr,a,l,2,74,NaN,4,695,NaN,...,2023-04,68224,1201,682241201,H,H,6822401,68701,44,68

In [5]:
df_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11702 entries, 0 to 11701
Data columns (total 52 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   idannonce                11702 non-null  object
 1   type_annonceur           11702 non-null  object
 2   typedebien               11702 non-null  object
 3   typedetransaction        11702 non-null  object
 4   etage                    11702 non-null  int64
 5   surface                  11702 non-null  int64
 6   surface_terrain          507 non-null    float64
 7   nb_pieces                11702 non-null  int64
 8   prix_bien                11702 non-null  int64
 9   prix_maison              0 non-null      float64
 10  prix_terrain             0 non-null      float64
 11  mensualiteFinance        11702 non-null  int64
 12  balcon                   11702 non-null  int64
 13  eau                      11702 non-null  int64
 14  bain                     11702 non-null  int64
 15  dpeL                     11702 non-null  object
 16  dpeC                     8835 non-null   float64
 17  mapCoordonneesLatitude   11702 non-null  float64
 18  mapCoordonneesLongitude  11702 non-null  float64
 19  annonce_exclusive        11702 non-null  object
 20  nb_etages                6631 non-null   float64
 21  parking                  0 non-null      float64
 22  places_parking           4082 non-null   float64
 23  cave                     4997 non-null   object
 24  exposition               11702 non-null  object
 25  ges_class                9424 non-null   object
 26  annee_construction       2275 non-null   float64
 27  nb_toilettes             4791 non-null   float64
 28  nb_terraces              1565 non-null   float64
 29  videophone               510 non-null    object
 30  porte_digicode           1978 non-null   object
 31  surface_balcon           193 non-null    float64
 32  ascenseur                6587 non-null   object
 33  nb_logements_copro       9 non-null      float64
 34  charges_copro            0 non-null      float64
 35  chauffage_energie        5635 non-null   object
 36  chauffage_systeme        3614 non-null   object
 37  chauffage_mode           7508 non-null   object
 38  categorie_annonceur      11702 non-null  object
 39  logement_neuf            11340 non-null  object
 40  duree_int                11448 non-null  float64
 41  typedebien_lite          11702 non-null  object
 42  date                     11702 non-null  object
 43  INSEE_COM                11702 non-null  int64
 44  IRIS                     11702 non-null  int64
 45  CODE_IRIS                11702 non-null  int64
 46  TYP_IRIS_x               11702 non-null  object
 47  TYP_IRIS_y               11702 non-null  object
 48  GRD_QUART                11702 non-null  int64
 49  UU2010                   11702 non-null  int64
 50  REG                      11702 non-null  int64
 51  DEP                      11702 non-null  int64
dtypes: float64(16), int64(15), object(21)
memory usage: 4.6+ MB

In [6]:
df_ventes.head()

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,hektor-robischung-2862,pr,a,v,0,64,NaN,3,128400,NaN,...,68113,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2006.25
1,apimo-82452515,pr,m,v,0,85,4950.0,4,189000,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,2223.53
2,immo-facile-52471952,pr,m,v,0,187,3182.0,9,282900,NaN,...,68000,44,68,NaN,NaN,NaN,NaN,NaN,NaN,1512.83
3,immo-facile-52477215,pr,a,v,0,76,NaN,4,79000,NaN,...,68000,44,68,7.93,3.0,0.092,7.93,3.0,0.092,1039.47
4,ag681088-383601401,pr,m,v,0,90,3071.0,5,317000,NaN,...,68000,44,68,9.77,2.0,0.033,9.77,2.0,0.033,3522.22

In [7]:
df_ventes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27737 entries, 0 to 27736
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   idannonce                27737 non-null  object
 1   type_annonceur           27737 non-null  object
 2   typedebien               27737 non-null  object
 3   typedetransaction        27737 non-null  object
 4   etage                    27737 non-null  int64
 5   surface                  27737 non-null  int64
 6   surface_terrain          11444 non-null  float64
 7   nb_pieces                27737 non-null  int64
 8   prix_bien                27737 non-null  int64
 9   prix_maison              437 non-null    float64
 10  prix_terrain             437 non-null    float64
 11  mensualiteFinance        27737 non-null  int64
 12  balcon                   27737 non-null  int64
 13  eau                      27737 non-null  int64
 14  bain                     27737 non-null  int64
 15  dpeL                     27737 non-null  object
 16  dpeC                     17150 non-null  float64
 17  mapCoordonneesLatitude   27737 non-null  float64
 18  mapCoordonneesLongitude  27737 non-null  float64
 19  annonce_exclusive        27737 non-null  object
 20  nb_etages                14859 non-null  float64
 21  parking                  27 non-null     object
 22  places_parking           10169 non-null  float64
 23  cave                     13247 non-null  object
 24  exposition               27737 non-null  object
 25  ges_class                19716 non-null  object
 26  annee_construction       9458 non-null   float64
 27  nb_toilettes             15436 non-null  float64
 28  nb_terraces              4099 non-null   float64
 29  videophone               135 non-null    object
 30  porte_digicode           4264 non-null   object
 31  surface_balcon           658 non-null    float64
 32  ascenseur                8750 non-null   object
 33  nb_logements_copro       7565 non-null   float64
 34  charges_copro            6677 non-null   float64
 35  chauffage_energie        12571 non-null  object
 36  chauffage_systeme        7627 non-null   object
 37  chauffage_mode           13610 non-null  object
 38  categorie_annonceur      27737 non-null  object
 39  logement_neuf            26998 non-null  object
 40  duree_int                26196 non-null  float64
 41  typedebien_lite          27737 non-null  object
 42  date                     27737 non-null  object
 43  INSEE_COM                27737 non-null  int64
 44  IRIS                     27737 non-null  int64
 45  CODE_IRIS                27737 non-null  int64
 46  TYP_IRIS_x               27737 non-null  object
 47  TYP_IRIS_y               27737 non-null  object
 48  GRD_QUART                27737 non-null  int64
 49  UU2010                   27737 non-null  int64
 50  REG                      27737 non-null  int64
 51  DEP                      27737 non-null  int64
 52  loyer_m2_median_n6       17485 non-null  float64
 53  nb_log_n6                17485 non-null  float64
 54  taux_rendement_n6        17485 non-null  float64
 55  loyer_m2_median_n7       19650 non-null  float64
 56  nb_log_n7                19650 non-null  float64
 57  taux_rendement_n7        19650 non-null  float64
 58  prix_m2_vente            27737 non-null  float64
dtypes: float64(22), int64(15), object(22)
memory usage: 12.5+ MB

In [8]:
df_unified = pd.concat([df_locations, df_ventes], ignore_index=True)

In [9]:
df_unified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39439 entries, 0 to 39438
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   idannonce                39439 non-null  object
 1   type_annonceur           39439 non-null  object
 2   typedebien               39439 non-null  object
 3   typedetransaction        39439 non-null  object
 4   etage                    39439 non-null  int64
 5   surface                  39439 non-null  int64
 6   surface_terrain          11951 non-null  float64
 7   nb_pieces                39439 non-null  int64
 8   prix_bien                39439 non-null  int64
 9   prix_maison              437 non-null    float64
 10  prix_terrain             437 non-null    float64
 11  mensualiteFinance        39439 non-null  int64
 12  balcon                   39439 non-null  int64
 13  eau                      39439 non-null  int64
 14  bain                     39439 non-null  int64
 15  dpeL                     39439 non-null  object
 16  dpeC                     25985 non-null  float64
 17  mapCoordonneesLatitude   39439 non-null  float64
 18  mapCoordonneesLongitude  39439 non-null  float64
 19  annonce_exclusive        39439 non-null  object
 20  nb_etages                21490 non-null  float64
 21  parking                  27 non-null     object
 22  places_parking           14251 non-null  float64
 23  cave                     18244 non-null  object
 24  exposition               39439 non-null  object
 25  ges_class                29140 non-null  object
 26  annee_construction       11733 non-null  float64
 27  nb_toilettes             20227 non-null  float64
 28  nb_terraces              5664 non-null   float64
 29  videophone               645 non-null    object
 30  porte_digicode           6242 non-null   object
 31  surface_balcon           851 non-null    float64
 32  ascenseur                15337 non-null  object
 33  nb_logements_copro       7574 non-null   float64
 34  charges_copro            6677 non-null   float64
 35  chauffage_energie        18206 non-null  object
 36  chauffage_systeme        11241 non-null  object
 37  chauffage_mode           21118 non-null  object
 38  categorie_annonceur      39439 non-null  object
 39  logement_neuf            38338 non-null  object
 40  duree_int                37644 non-null  float64
 41  typedebien_lite          39439 non-null  object
 42  date                     39439 non-null  object
 43  INSEE_COM                39439 non-null  int64
 44  IRIS                     39439 non-null  int64
 45  CODE_IRIS                39439 non-null  int64
 46  TYP_IRIS_x               39439 non-null  object
 47  TYP_IRIS_y               39439 non-null  object
 48  GRD_QUART                39439 non-null  int64
 49  UU2010                   39439 non-null  int64
 50  REG                      39439 non-null  int64
 51  DEP                      39439 non-null  int64
 52  loyer_m2_median_n6       17485 non-null  float64
 53  nb_log_n6                17485 non-null  float64
 54  taux_rendement_n6        17485 non-null  float64
 55  loyer_m2_median_n7       19650 non-null  float64
 56  nb_log_n7                19650 non-null  float64
 57  taux_rendement_n7        19650 non-null  float64
 58  prix_m2_vente            27737 non-null  float64
dtypes: float64(22), int64(15), object(22)
memory usage: 17.8+ MB

In [10]:
#df_unified.to_csv('../data/processed/dataset_unifie.csv', index=False)