In [2]:
import pandas as pd

In [3]:
#library imports API data
#import

In [9]:
# Region: Paris (75)
df_locations = pd.read_csv('../data/df_annonces_gps_iris_locations_75.csv',sep=';')
df_ventes = pd.read_csv('../data/df_annonces_gps_iris_ventes_75.csv',sep=';')

C:\Users\CYTech Student\AppData\Local\Temp\ipykernel_1140\969437883.py:2: DtypeWarning: Columns (19,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_locations = pd.read_csv('../data/df_annonces_gps_iris_locations_75.csv',sep=';')
C:\Users\CYTech Student\AppData\Local\Temp\ipykernel_1140\969437883.py:3: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ventes = pd.read_csv('../data/df_annonces_gps_iris_ventes_75.csv',sep=';')

In [10]:
df_locations.head()

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,date,INSEE_COM,IRIS,CODE_IRIS,TYP_IRIS_x,TYP_IRIS_y,GRD_QUART,UU2010,REG,DEP
0,century-21-202_2864_10012,pr,a,l,0,74,NaN,3,2790,NaN,...,2026-02,75109,3301,751093301,H,H,7510933,851,11,75
1,century-21-202_2864_10010,pr,a,l,2,113,NaN,4,3840,NaN,...,2026-02,75109,3301,751093301,H,H,7510933,851,11,75
2,ag757532-513493781,pr,a,l,2,34,NaN,1,1650,NaN,...,2026-02,75109,3303,751093303,H,H,7510933,851,11,75
3,ag752861-512430734,pr,a,l,5,72,NaN,3,3380,NaN,...,2026-02,75109,3403,751093403,A,H,7510933,851,11,75
4,ag752352-513486446,pr,a,l,4,29,NaN,1,1090,NaN,...,2026-02,75109,3504,751093504,A,H,7510933,851,11,75

In [11]:
df_locations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111901 entries, 0 to 111900
Data columns (total 52 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   idannonce                111901 non-null  object
 1   type_annonceur           111901 non-null  object
 2   typedebien               111901 non-null  object
 3   typedetransaction        111901 non-null  object
 4   etage                    111901 non-null  int64
 5   surface                  111901 non-null  int64
 6   surface_terrain          174 non-null     float64
 7   nb_pieces                111901 non-null  int64
 8   prix_bien                111901 non-null  int64
 9   prix_maison              0 non-null       float64
 10  prix_terrain             0 non-null       float64
 11  mensualiteFinance        111901 non-null  int64
 12  balcon                   111901 non-null  int64
 13  eau                      111901 non-null  int64
 14  bain                     111901 non-null  int64
 15  dpeL                     111901 non-null  object
 16  dpeC                     65815 non-null   float64
 17  mapCoordonneesLatitude   111901 non-null  float64
 18  mapCoordonneesLongitude  111901 non-null  float64
 19  annonce_exclusive        111901 non-null  object
 20  nb_etages                41590 non-null   float64
 21  parking                  10 non-null      object
 22  places_parking           15156 non-null   float64
 23  cave                     31056 non-null   object
 24  exposition               111901 non-null  object
 25  ges_class                68719 non-null   object
 26  annee_construction       21305 non-null   float64
 27  nb_toilettes             40003 non-null   float64
 28  nb_terraces              9885 non-null    float64
 29  videophone               1056 non-null    object
 30  porte_digicode           34855 non-null   object
 31  surface_balcon           947 non-null     float64
 32  ascenseur                66032 non-null   object
 33  nb_logements_copro       698 non-null     float64
 34  charges_copro            0 non-null       float64
 35  chauffage_energie        41827 non-null   object
 36  chauffage_systeme        22102 non-null   object
 37  chauffage_mode           60396 non-null   object
 38  categorie_annonceur      111840 non-null  object
 39  logement_neuf            98439 non-null   object
 40  duree_int                111180 non-null  float64
 41  typedebien_lite          111901 non-null  object
 42  date                     111901 non-null  object
 43  INSEE_COM                111901 non-null  int64
 44  IRIS                     111901 non-null  int64
 45  CODE_IRIS                111901 non-null  int64
 46  TYP_IRIS_x               111901 non-null  object
 47  TYP_IRIS_y               111901 non-null  object
 48  GRD_QUART                111901 non-null  int64
 49  UU2010                   111901 non-null  int64
 50  REG                      111901 non-null  int64
 51  DEP                      111901 non-null  int64
dtypes: float64(15), int64(15), object(22)
memory usage: 44.4+ MB

In [12]:
df_ventes.head()

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,iad-france-1999597,pr,a,v,4,70,NaN,4,820000,NaN,...,851,11,75,31.78,14.0,0.033,32.47,260.0,0.033,11714.29
1,apimo-86694012,pr,a,v,2,155,NaN,6,1990000,NaN,...,851,11,75,23.18,1.0,0.022,29.14,74.0,0.027,12838.71
2,apimo-86677654,pr,a,v,2,155,NaN,6,1990000,NaN,...,851,11,75,23.18,1.0,0.022,29.14,74.0,0.027,12838.71
3,ag756339-511400033,pr,a,v,4,55,NaN,3,665000,NaN,...,851,11,75,35.53,28.0,0.035,34.16,652.0,0.034,12090.91
4,hektor-equinimo-6700,pr,a,v,1,63,NaN,3,659000,NaN,...,851,11,75,35.53,28.0,0.041,34.16,652.0,0.039,10460.32

In [13]:
df_ventes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170181 entries, 0 to 170180
Data columns (total 59 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   idannonce                170181 non-null  object
 1   type_annonceur           170181 non-null  object
 2   typedebien               170181 non-null  object
 3   typedetransaction        170181 non-null  object
 4   etage                    170181 non-null  int64
 5   surface                  170181 non-null  int64
 6   surface_terrain          1821 non-null    float64
 7   nb_pieces                170181 non-null  int64
 8   prix_bien                170181 non-null  int64
 9   prix_maison              1 non-null       float64
 10  prix_terrain             1 non-null       float64
 11  mensualiteFinance        170181 non-null  int64
 12  balcon                   170181 non-null  int64
 13  eau                      170181 non-null  int64
 14  bain                     170181 non-null  int64
 15  dpeL                     170181 non-null  object
 16  dpeC                     125853 non-null  float64
 17  mapCoordonneesLatitude   170181 non-null  float64
 18  mapCoordonneesLongitude  170181 non-null  float64
 19  annonce_exclusive        170181 non-null  object
 20  nb_etages                128694 non-null  float64
 21  parking                  46 non-null      object
 22  places_parking           27318 non-null   float64
 23  cave                     83101 non-null   object
 24  exposition               170181 non-null  object
 25  ges_class                137033 non-null  object
 26  annee_construction       61030 non-null   float64
 27  nb_toilettes             92219 non-null   float64
 28  nb_terraces              19077 non-null   float64
 29  videophone               2594 non-null    object
 30  porte_digicode           75971 non-null   object
 31  surface_balcon           5509 non-null    float64
 32  ascenseur                117893 non-null  object
 33  nb_logements_copro       94807 non-null   float64
 34  charges_copro            108454 non-null  float64
 35  chauffage_energie        94844 non-null   object
 36  chauffage_systeme        58551 non-null   object
 37  chauffage_mode           120236 non-null  object
 38  categorie_annonceur      170078 non-null  object
 39  logement_neuf            167353 non-null  object
 40  duree_int                166947 non-null  float64
 41  typedebien_lite          170181 non-null  object
 42  date                     170181 non-null  object
 43  INSEE_COM                170181 non-null  int64
 44  IRIS                     170181 non-null  int64
 45  CODE_IRIS                170181 non-null  int64
 46  TYP_IRIS_x               170181 non-null  object
 47  TYP_IRIS_y               170181 non-null  object
 48  GRD_QUART                170181 non-null  int64
 49  UU2010                   170181 non-null  int64
 50  REG                      170181 non-null  int64
 51  DEP                      170181 non-null  int64
 52  loyer_m2_median_n6       161794 non-null  float64
 53  nb_log_n6                161794 non-null  float64
 54  taux_rendement_n6        161794 non-null  float64
 55  loyer_m2_median_n7       169413 non-null  float64
 56  nb_log_n7                169413 non-null  float64
 57  taux_rendement_n7        169413 non-null  float64
 58  prix_m2_vente            170181 non-null  float64
dtypes: float64(22), int64(15), object(22)
memory usage: 76.6+ MB

In [14]:
df_unified = pd.concat([df_locations, df_ventes], ignore_index=True)

In [15]:
df_unified.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282082 entries, 0 to 282081
Data columns (total 59 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   idannonce                282082 non-null  object
 1   type_annonceur           282082 non-null  object
 2   typedebien               282082 non-null  object
 3   typedetransaction        282082 non-null  object
 4   etage                    282082 non-null  int64
 5   surface                  282082 non-null  int64
 6   surface_terrain          1995 non-null    float64
 7   nb_pieces                282082 non-null  int64
 8   prix_bien                282082 non-null  int64
 9   prix_maison              1 non-null       float64
 10  prix_terrain             1 non-null       float64
 11  mensualiteFinance        282082 non-null  int64
 12  balcon                   282082 non-null  int64
 13  eau                      282082 non-null  int64
 14  bain                     282082 non-null  int64
 15  dpeL                     282082 non-null  object
 16  dpeC                     191668 non-null  float64
 17  mapCoordonneesLatitude   282082 non-null  float64
 18  mapCoordonneesLongitude  282082 non-null  float64
 19  annonce_exclusive        282082 non-null  object
 20  nb_etages                170284 non-null  float64
 21  parking                  56 non-null      object
 22  places_parking           42474 non-null   float64
 23  cave                     114157 non-null  object
 24  exposition               282082 non-null  object
 25  ges_class                205752 non-null  object
 26  annee_construction       82335 non-null   float64
 27  nb_toilettes             132222 non-null  float64
 28  nb_terraces              28962 non-null   float64
 29  videophone               3650 non-null    object
 30  porte_digicode           110826 non-null  object
 31  surface_balcon           6456 non-null    float64
 32  ascenseur                183925 non-null  object
 33  nb_logements_copro       95505 non-null   float64
 34  charges_copro            108454 non-null  float64
 35  chauffage_energie        136671 non-null  object
 36  chauffage_systeme        80653 non-null   object
 37  chauffage_mode           180632 non-null  object
 38  categorie_annonceur      281918 non-null  object
 39  logement_neuf            265792 non-null  object
 40  duree_int                278127 non-null  float64
 41  typedebien_lite          282082 non-null  object
 42  date                     282082 non-null  object
 43  INSEE_COM                282082 non-null  int64
 44  IRIS                     282082 non-null  int64
 45  CODE_IRIS                282082 non-null  int64
 46  TYP_IRIS_x               282082 non-null  object
 47  TYP_IRIS_y               282082 non-null  object
 48  GRD_QUART                282082 non-null  int64
 49  UU2010                   282082 non-null  int64
 50  REG                      282082 non-null  int64
 51  DEP                      282082 non-null  int64
 52  loyer_m2_median_n6       161794 non-null  float64
 53  nb_log_n6                161794 non-null  float64
 54  taux_rendement_n6        161794 non-null  float64
 55  loyer_m2_median_n7       169413 non-null  float64
 56  nb_log_n7                169413 non-null  float64
 57  taux_rendement_n7        169413 non-null  float64
 58  prix_m2_vente            170181 non-null  float64
dtypes: float64(22), int64(15), object(22)
memory usage: 127.0+ MB

In [ ]:
#df_unified.to_csv('../data/dataset_unifie.csv', index=False)